<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Resona.Cloud.Server</AssemblyName>
    <RootNamespace>Resona.Cloud.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Resona.Core\Resona.Core.csproj" />
    <PackageReference Include="Npgsql" Version="9.0.5" />
  </ItemGroup>
</Project>
