// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misa.Domain.Features.Audit;
using Misa.Domain.Features.Entities.Base;
using Misa.Domain.Features.Entities.Extensions.Items.Base;
using Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks;
using Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling;
using Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions;
using Misa.Infrastructure.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Misa.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "change_type", new[] { "category", "deadline", "priority", "state", "title" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "priority", new[] { "critical", "high", "low", "medium", "none", "urgent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_action_type", new[] { "create_task", "deadline", "none", "recurring" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_execution_state", new[] { "claimed", "failed", "pending", "running", "skipped", "succeeded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_frequency_type", new[] { "days", "hours", "minutes", "months", "once", "weeks", "years" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_misfire_policy", new[] { "catchup", "run_once", "skip" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_concentration_type", new[] { "deep_focus", "distracted", "focused", "hyperfocus", "none", "unfocused_but_calm" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_efficiency_type", new[] { "high_output", "low_output", "none", "peak_performance", "steady_output" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_state", new[] { "ended", "paused", "running" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_category", new[] { "other", "personal", "school", "work" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow", new[] { "deadline", "scheduling", "task" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Misa.Domain.Features.Audit.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<ChangeType>("ChangeType")
                        .HasColumnType("change_type")
                        .HasColumnName("field");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ValueAfter")
                        .HasColumnType("text")
                        .HasColumnName("value_after");

                    b.Property<string>("ValueBefore")
                        .HasColumnType("text")
                        .HasColumnName("value_before");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("audit_changes", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("InteractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interacted_at_utc");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Workflow>("Workflow")
                        .HasColumnType("workflow")
                        .HasColumnName("workflow");

                    b.HasKey("Id");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Priority>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("priority")
                        .HasDefaultValue(Priority.None)
                        .HasColumnName("priority");

                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.ToTable("item_states", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Draft",
                            Synopsis = "Entwurf; noch nie daran gearbeitet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Undefined",
                            Synopsis = "Unklar; muss präzisiert werden"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scheduled",
                            Synopsis = "Geplant für einen zukünftigen Zeitpunkt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "InProgress",
                            Synopsis = "Bereits bearbeitet, aktuell keine aktive Session"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Active",
                            Synopsis = "Aktive Session läuft"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Paused",
                            Synopsis = "Session pausiert (max. 6h, danach Auto-Fortsetzung)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pending",
                            Synopsis = "Zurückgestellt; lange nicht bearbeitet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "WaitForResponse",
                            Synopsis = "Wartet auf Rückmeldung einer Person oder Stelle"
                        },
                        new
                        {
                            Id = 9,
                            Name = "BlockedByRelationship",
                            Synopsis = "Blockiert durch Relation oder Abhängigkeit"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Done",
                            Synopsis = "Erfolgreich abgeschlossen"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Canceled",
                            Synopsis = "Abgebrochen; nicht weiter erforderlich"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Failed",
                            Synopsis = "Gescheitert; Ziel nicht erreicht"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Expired",
                            Synopsis = "Automatisch abgelaufen (Deadline überschritten)"
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TaskCategory>("Category")
                        .HasColumnType("task_category")
                        .HasColumnName("category");

                    b.HasKey("Id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<ScheduleActionType>("ActionType")
                        .HasColumnType("schedule_action_type")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("ActiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from_utc");

                    b.Property<DateTimeOffset?>("ActiveUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_until_utc");

                    b.PrimitiveCollection<int[]>("ByDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_day");

                    b.PrimitiveCollection<int[]>("ByMonth")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month");

                    b.PrimitiveCollection<int[]>("ByMonthDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month_day");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("FrequencyInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("frequency_interval");

                    b.Property<DateTimeOffset?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at_utc");

                    b.Property<int>("LookaheadLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("lookahead_limit");

                    b.Property<ScheduleMisfirePolicy>("MisfirePolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("schedule_misfire_policy")
                        .HasDefaultValue(ScheduleMisfirePolicy.Catchup)
                        .HasColumnName("misfire_policy");

                    b.Property<DateTimeOffset?>("NextAllowedExecutionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_allowed_execution_at_utc");

                    b.Property<DateTimeOffset?>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at_utc");

                    b.Property<int?>("OccurrenceCountLimit")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count_limit");

                    b.Property<TimeSpan?>("OccurrenceTtl")
                        .HasColumnType("interval")
                        .HasColumnName("occurrence_ttl");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<ScheduleFrequencyType>("ScheduleFrequencyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("schedule_frequency_type")
                        .HasDefaultValue(ScheduleFrequencyType.Once)
                        .HasColumnName("frequency_type");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid?>("TargetItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_item_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("scheduler", null, t =>
                        {
                            t.HasCheckConstraint("ck_scheduler_active_date", "active_until_utc IS NULL OR active_until_utc > active_from_utc");

                            t.HasCheckConstraint("ck_scheduler_active_time", "(start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL AND start_time < end_time)");

                            t.HasCheckConstraint("ck_scheduler_lookahead_limit_gt_0", "lookahead_limit > 0");

                            t.HasCheckConstraint("ck_scheduler_next_due_ge_last_run", "next_due_at_utc IS NULL OR last_run_at_utc IS NULL OR next_due_at_utc >= last_run_at_utc");

                            t.HasCheckConstraint("ck_scheduler_occurrence_count_limit_ge_1", "occurrence_count_limit IS NULL OR occurrence_count_limit >= 1");

                            t.HasCheckConstraint("ck_scheduler_ttl_timespan", "occurrence_ttl IS NULL OR occurrence_ttl > INTERVAL '0'");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<Guid>("SchedulerId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduler_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<SchedulerExecutionStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("schedule_execution_state")
                        .HasDefaultValue(SchedulerExecutionStatus.Pending)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SchedulerId", "ScheduledForUtc")
                        .IsUnique();

                    b.ToTable("scheduler_execution_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_schedexec_after_claimed_requires_started", "status IN ('pending','claimed') OR started_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_claimed_le_started_or_started_null", "started_at_utc IS NULL OR claimed_at_utc <= started_at_utc");

                            t.HasCheckConstraint("ck_schedexec_done_requires_finished", "status NOT IN ('succeeded','failed','skipped') OR finished_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_not_pending_requires_claimed", "status = 'pending' OR claimed_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_pending_has_no_timestamps", "status <> 'pending' OR (claimed_at_utc IS NULL AND started_at_utc IS NULL AND finished_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_schedexec_started_le_finished_or_finished_null", "finished_at_utc IS NULL OR started_at_utc <= finished_at_utc");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AutoStopReason")
                        .HasColumnType("text")
                        .HasColumnName("auto_stop_reason");

                    b.Property<SessionConcentrationType>("Concentration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_concentration_type")
                        .HasDefaultValue(SessionConcentrationType.None)
                        .HasColumnName("concentration");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<SessionEfficiencyType>("Efficiency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_efficiency_type")
                        .HasDefaultValue(SessionEfficiencyType.None)
                        .HasColumnName("efficiency");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<TimeSpan?>("PlannedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("planned_duration");

                    b.Property<SessionState>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_state")
                        .HasDefaultValue(SessionState.Running)
                        .HasColumnName("state");

                    b.Property<bool>("StopAutomatically")
                        .HasColumnType("boolean")
                        .HasColumnName("stop_automatically");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<bool?>("WasAutomaticallyStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("was_automatically_stopped");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_planned_duration", "planned_duration IS NULL OR (planned_duration > INTERVAL '0 seconds' AND planned_duration < INTERVAL '1 day')");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text")
                        .HasColumnName("pause_reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("session_segments", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_segments_ended_after_started", "ended_at_utc IS NULL OR started_at_utc <= ended_at_utc");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Descriptions.Description", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("descriptions", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Audit.AuditChange", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Changes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", "Entity")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Item")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Item")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", "Scheduler")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("SchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheduler");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", null)
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Descriptions.Description", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
