// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misa.Domain.Features.Audit;
using Misa.Domain.Features.Entities.Base;
using Misa.Domain.Features.Entities.Extensions.Items.Base;
using Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks;
using Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling;
using Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions;
using Misa.Domain.Features.Messaging;
using Misa.Infrastructure.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Misa.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "change_type", new[] { "category", "deadline", "priority", "state", "title" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_type", new[] { "scheduler_created_task" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "outbox_event_state", new[] { "pending", "processed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "priority", new[] { "critical", "high", "low", "medium", "none", "urgent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_action_type", new[] { "create_task", "deadline", "none", "recurring" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_frequency_type", new[] { "days", "hours", "minutes", "months", "once", "weeks", "years" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_misfire_policy", new[] { "catchup", "run_once", "skip" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "scheduler_execution_status", new[] { "claimed", "failed", "pending", "running", "skipped", "succeeded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_concentration_type", new[] { "deep_focus", "distracted", "focused", "hyperfocus", "none", "unfocused_but_calm" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_efficiency_type", new[] { "high_output", "low_output", "none", "peak_performance", "steady_output" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "session_state", new[] { "ended", "paused", "running" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_category", new[] { "other", "personal", "school", "work" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow", new[] { "deadline", "scheduling", "task" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Misa.Domain.Features.Audit.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<ChangeType>("ChangeType")
                        .HasColumnType("change_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ValueAfter")
                        .HasColumnType("text");

                    b.Property<string>("ValueBefore")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("AuditChanges");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InteractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Workflow>("Workflow")
                        .HasColumnType("workflow");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Priority>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("priority")
                        .HasDefaultValue(Priority.None);

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TaskCategory>("Category")
                        .HasColumnType("task_category");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<ScheduleActionType>("ActionType")
                        .HasColumnType("schedule_action_type");

                    b.Property<DateTimeOffset>("ActiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActiveUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("ByDay")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByMonth")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByMonthDay")
                        .HasColumnType("integer[]");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FrequencyInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LookaheadLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<ScheduleMisfirePolicy>("MisfirePolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("schedule_misfire_policy")
                        .HasDefaultValue(ScheduleMisfirePolicy.Catchup);

                    b.Property<DateTimeOffset?>("NextAllowedExecutionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OccurrenceCountLimit")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("OccurrenceTtl")
                        .HasColumnType("interval");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<ScheduleFrequencyType>("ScheduleFrequencyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("schedule_frequency_type")
                        .HasDefaultValue(ScheduleFrequencyType.Once);

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("TargetItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedulers", t =>
                        {
                            t.HasCheckConstraint("ck_scheduler_active_date", "\"ActiveUntilUtc\" IS NULL OR \"ActiveUntilUtc\" > \"ActiveFromUtc\"");

                            t.HasCheckConstraint("ck_scheduler_active_time", "(\"StartTime\" IS NULL AND \"EndTime\" IS NULL) OR (\"StartTime\" IS NOT NULL AND \"EndTime\" IS NOT NULL AND \"StartTime\" < \"EndTime\")");

                            t.HasCheckConstraint("ck_scheduler_lookahead_limit_gt_0", "\"LookaheadLimit\" > 0");

                            t.HasCheckConstraint("ck_scheduler_next_due_ge_last_run", "\"NextDueAtUtc\" IS NULL OR \"LastRunAtUtc\" IS NULL OR \"NextDueAtUtc\" >= \"LastRunAtUtc\"");

                            t.HasCheckConstraint("ck_scheduler_occurrence_count_limit_ge_1", "\"OccurrenceCountLimit\" IS NULL OR \"OccurrenceCountLimit\" >= 0");

                            t.HasCheckConstraint("ck_scheduler_ttl_timespan", "\"OccurrenceTtl\" IS NULL OR \"OccurrenceTtl\" > INTERVAL '0'");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchedulerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<SchedulerExecutionStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("scheduler_execution_status")
                        .HasDefaultValue(SchedulerExecutionStatus.Pending);

                    b.HasKey("Id");

                    b.HasIndex("SchedulerId", "ScheduledForUtc")
                        .IsUnique();

                    b.ToTable("SchedulerExecutionLogs", t =>
                        {
                            t.HasCheckConstraint("ck_schedexec_after_claimed_requires_started", "\"Status\" IN ('pending','claimed') OR \"StartedAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_claimed_le_started_or_started_null", "\"StartedAtUtc\" IS NULL OR \"ClaimedAtUtc\" <= \"StartedAtUtc\"");

                            t.HasCheckConstraint("ck_schedexec_done_requires_finished", "\"Status\" NOT IN ('succeeded','failed','skipped') OR \"FinishedAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_not_pending_requires_claimed", "\"Status\" = 'pending' OR \"ClaimedAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("ck_schedexec_pending_has_no_timestamps", "\"Status\" <> 'pending' OR (\"ClaimedAtUtc\" IS NULL AND \"StartedAtUtc\" IS NULL AND \"FinishedAtUtc\" IS NULL)");

                            t.HasCheckConstraint("ck_schedexec_started_le_finished_or_finished_null", "\"FinishedAtUtc\" IS NULL OR \"StartedAtUtc\" <= \"FinishedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AutoStopReason")
                        .HasColumnType("text");

                    b.Property<SessionConcentrationType>("Concentration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_concentration_type")
                        .HasDefaultValue(SessionConcentrationType.None);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<SessionEfficiencyType>("Efficiency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_efficiency_type")
                        .HasDefaultValue(SessionEfficiencyType.None);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("PlannedDuration")
                        .HasColumnType("interval");

                    b.Property<SessionState>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("session_state")
                        .HasDefaultValue(SessionState.Running);

                    b.Property<bool>("StopAutomatically")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<bool?>("WasAutomaticallyStopped")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionSegments");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Description", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Messaging.Outbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<OutboxEventState>("EventState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("outbox_event_state")
                        .HasDefaultValue(OutboxEventState.Pending);

                    b.Property<EventType>("EventType")
                        .HasColumnType("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Misa.Domain.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Misa.Domain.Features.Audit.AuditChange", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Changes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", "Entity")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Item")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Extensions.Tasks.Task", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "Item")
                        .WithOne()
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", "Scheduler")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("SchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheduler");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", null)
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Description", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
