// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling;
using Misa.Infrastructure.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Misa.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20260122155836_FixDescriptionsCreatedAtDefault")]
    partial class FixDescriptionsCreatedAtDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "scheduler_misfire_policy", new[] { "catchup", "run_once", "skip" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Misa.Domain.Features.Actions.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<string>("ValueAfter")
                        .HasColumnType("text")
                        .HasColumnName("value_after");

                    b.Property<string>("ValueBefore")
                        .HasColumnType("text")
                        .HasColumnName("value_before");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("TypeId");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Actions.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("action_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("InteractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interacted_at_utc");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.ToTable("entity_workflow_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("workflow_category_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("EntityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StateId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.ToTable("item_priorities", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.ToTable("item_states", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Deadlines.ScheduledDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeadlineAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at_utc");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("scheduled_deadlines", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ActiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from_utc");

                    b.Property<DateTimeOffset?>("ActiveUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_until_utc");

                    b.PrimitiveCollection<int[]>("ByDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_day");

                    b.PrimitiveCollection<int[]>("ByMonth")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month");

                    b.PrimitiveCollection<int[]>("ByMonthDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month_day");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("FrequencyInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("frequency_interval");

                    b.Property<int>("FrequencyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_type_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at_utc");

                    b.Property<int>("LookaheadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("lookahead_count");

                    b.Property<ScheduleMisfirePolicy>("MisfirePolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("scheduler_misfire_policy")
                        .HasDefaultValue(ScheduleMisfirePolicy.Catchup)
                        .HasColumnName("misfire_policy");

                    b.Property<DateTimeOffset?>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at_utc");

                    b.Property<int?>("OccurrenceCountLimit")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count_limit");

                    b.Property<TimeSpan?>("OccurrenceTtl")
                        .HasColumnType("interval")
                        .HasColumnName("occurrence_ttl");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyTypeId");

                    b.HasIndex("ItemId");

                    b.ToTable("scheduler", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<Guid>("SchedulerId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduler_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SchedulerId");

                    b.ToTable("scheduler_execution_log", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerFrequencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.ToTable("scheduler_frequency_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutoStopReason")
                        .HasColumnType("text")
                        .HasColumnName("auto_stop_reason");

                    b.Property<int?>("ConcentrationId")
                        .HasColumnType("integer")
                        .HasColumnName("concentration_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("EfficiencyId")
                        .HasColumnType("integer")
                        .HasColumnName("efficiency_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<TimeSpan?>("PlannedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("planned_duration");

                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.Property<bool>("StopAutomatically")
                        .HasColumnType("boolean")
                        .HasColumnName("stop_automatically");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<bool?>("WasAutomaticallyStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("was_automatically_stopped");

                    b.HasKey("Id");

                    b.HasIndex("ConcentrationId");

                    b.HasIndex("EfficiencyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StateId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionConcentrationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("session_concentration_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionEfficiencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("session_efficiency_types", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text")
                        .HasColumnName("pause_reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("session_segments", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionStates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("session_states", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Descriptions.Description", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("descriptions", (string)null);
                });

            modelBuilder.Entity("Misa.Domain.Features.Actions.Action", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Actions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Actions.ActionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Category", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", "Entity")
                        .WithOne("Item")
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Entity");

                    b.Navigation("Priority");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Deadlines.ScheduledDeadline", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", null)
                        .WithOne("ScheduledDeadline")
                        .HasForeignKey("Misa.Domain.Features.Entities.Extensions.Items.Features.Deadlines.ScheduledDeadline", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerFrequencyType", "FrequencyType")
                        .WithMany()
                        .HasForeignKey("FrequencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrequencyType");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.SchedulerExecutionLog", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", "Scheduler")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("SchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheduler");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionConcentrationType", "Concentration")
                        .WithMany()
                        .HasForeignKey("ConcentrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionEfficiencyType", "Efficiency")
                        .WithMany()
                        .HasForeignKey("EfficiencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionStates", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concentration");

                    b.Navigation("Efficiency");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.SessionSegment", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", null)
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Features.Descriptions.Description", b =>
                {
                    b.HasOne("Misa.Domain.Features.Entities.Base.Entity", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Base.Entity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Descriptions");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Base.Item", b =>
                {
                    b.Navigation("ScheduledDeadline");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Scheduling.Scheduler", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("Misa.Domain.Features.Entities.Extensions.Items.Features.Sessions.Session", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
